print("Before:")
print_formula(formula)
node = decide(formula)
update_formula(node, formula)
print("After 1 decision:")
print_formula(formula)
node = decide(formula)
update_formula(node, formula)
print("After 2 decision:")
print_formula(formula)
node = decide(formula)
update_formula(node, formula)
print("After 3 decision:")
print_formula(formula)
print(check_unit(formula))